server:
  port: 8080

logging:
  level:
    ca.tetervak: trace

spring:
  application:
    name: CityDataServer

    #spring.jpa.open-in-view=true
  datasource:
      url: jdbc:h2:mem:default
      driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #spring.jpa.hibernate.ddl-auto=none
  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
            # This ID must match what you allow in the Auth Server
          auth-server-client:
            client-id: swagger-client
            client-secret: swagger-secret
            authorization-grant-type: authorization_code
            scope: openid, profile, read
            # The standard Spring Security callback path
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          auth-server-client:
            # The URL of your Identity Service
            issuer-uri: http://localhost:9000
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

springdoc:
  api-docs:
    path: /cities-api-docs

  swagger-ui:
    path: /swagger-ui.html
    #path: /

    # These properties ARE resolved and officially supported
    #oauth:
    #  client-id: swagger-client
    #  client-secret: swagger-secret
    # Ensures the "Try it out" button is always visible
    try-it-out-enabled: true







