server:
  port: 8080

logging:
  level:
    ca.tetervak: trace
    org.springframework.security: trace # Added for easier debugging

spring:
  application:
    name: CityDataServer

  # FIXED INDENTATION BELOW
  datasource:
    url: jdbc:h2:mem:default
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          auth-server-client:
            client-id: swagger-client
            client-secret: swagger-secret
            authorization-grant-type: authorization_code
            # Match exactly with what is in the Auth Server RegisteredClient bean
            scope: openid, profile, read
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          auth-server-client:
            issuer-uri: http://localhost:9000
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

springdoc:
  api-docs:
    path: /cities-api-docs
  swagger-ui:
    path: /swagger-ui.html
    # Uncomment these to save time during testing
    oauth:
      client-id: swagger-client
      client-secret: swagger-secret
    try-it-out-enabled: true